Creating Numpy **Arrays**

In [2]:
import numpy as np


In [ ]:
a=np.array([1,2,3])
print(type(a))  #vector

<class 'numpy.ndarray'>


In [ ]:
b=np.array([[1,2,3],[4,5,6]])  #metrix
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])  #tensor
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
np.array([1,2,3],dtype=float)  #dtype

array([1., 2., 3.])

In [ ]:
np.array([1,2,3],dtype=np.double)

array([1., 2., 3.])

In [ ]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
#with reshape
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
# np.random
np.random.random((3,4))

array([[0.99845407, 0.22863568, 0.07952214, 0.53123506],
       [0.90801466, 0.18543052, 0.78512606, 0.27948686],
       [0.68763829, 0.14738911, 0.45275111, 0.16930168]])

In [ ]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array **Attributes**

In [ ]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
a1  #1D array vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [ ]:
a2 #matrix

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a3 #3d tensor

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1.ndim   #ndim tells dimensions

1

In [ ]:
a2.ndim

2

In [ ]:
a3.ndim

3

In [ ]:
a1.shape   #shape

(10,)

In [ ]:
print(a1.shape)
a1

(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [ ]:
print(a2.shape)
a2

(3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# size
print(a1.size)
print(a1)

10
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(a2.size)
print(a2)

12
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [ ]:
print(a3.size)
print(a3)

8
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
# itemsize
a1.itemsize

4

In [ ]:
a2.itemsize

8

In [ ]:
a3.itemsize

8

In [ ]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


**Changing Datatype**

In [ ]:
# astype
a3.dtype

dtype('int64')

In [ ]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

**Array Operations**

In [ ]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [ ]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# scalar operations

# arithmetic
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
a1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [ ]:
a1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
a1/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [ ]:
#scalar opt
a2>=15

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
# vector operations
# arithmetic
a1+a2
#a1-a2
#a1*a2
#a1/a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

**Array Functions**

In [ ]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[10., 58., 53.],
       [ 8., 98., 71.],
       [ 0., 73.,  8.]])

In [ ]:
# max/min/sum/prod

np.max(a1)

np.float64(88.0)

In [ ]:
np.min(a1)

np.float64(10.0)

In [ ]:
np.sum(a1)

np.float64(471.0)

In [ ]:
np.prod(a1)

np.float64(544773972600000.0)

In [ ]:
#each row max item
# axis=0 -> col and 1 -> row

np.max(a1,axis=1)

array([58., 98., 73.])

In [ ]:
# mean/median/std/var
np.mean(a1)

np.float64(42.111111111111114)

In [ ]:
np.mean(a1,axis=1)

array([40.33333333, 59.        , 27.        ])

In [ ]:
np.median(a1,axis=1)

array([53., 71.,  8.])

In [ ]:
np.std(a1,axis=1)

array([21.54581681, 37.70941527, 32.69046752])

In [ ]:
np.var(a1,axis=1)

array([ 464.22222222, 1422.        , 1068.66666667])

In [ ]:
# trigonomoetric functions
np.sin(a1)

array([[-0.54402111,  0.99287265,  0.39592515],
       [ 0.98935825, -0.57338187,  0.95105465],
       [ 0.        , -0.67677196,  0.98935825]])

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [ ]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents
np.log(a3)



array([[2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334],
       [2.89037176, 2.94443898, 2.99573227],
       [3.04452244, 3.09104245, 3.13549422]])

In [ ]:
np.exp(a3)

array([[1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07],
       [6.56599691e+07, 1.78482301e+08, 4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09]])

In [ ]:
# round/floor/ceil
np.random.random((2,3))*100

array([[81.16013218,  1.01452863, 32.67681415],
       [55.6501126 , 85.45567781, 47.19700615]])

In [ ]:
np.round(np.random.random((2,3))*100)

array([[ 1., 59., 20.],
       [73., 31., 16.]])

In [ ]:
np.floor(np.random.random((2,3))*100)

array([[ 0., 39., 38.],
       [39., 87., 50.]])

In [ ]:
np.ceil(np.random.random((2,3))*100)

array([[72., 88., 82.],
       [66.,  8.,  5.]])

### Indexing and Slicing

In [3]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [ ]:
a1 #1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2  #2D

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a3  #3D

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
#Last element
a1[-1]

np.int64(9)

In [ ]:
#first
a1[0]

np.int64(0)

In [ ]:
a2[2,3]

np.int64(11)

In [ ]:
a2[1,0]

np.int64(4)

In [ ]:
a3[1,0,1]

np.int64(5)

In [ ]:
a3[0,1,0]

np.int64(2)

In [ ]:
a3[0,0,0]

np.int64(0)

In [ ]:
a3[1,1,0]

np.int64(6)

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5]

array([2, 3, 4])

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0,:]  #1st row

array([0, 1, 2, 3])

In [ ]:
a2[:,2] #3rd col

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [16]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

In [ ]:
a3[1,:,1]

array([10, 13, 16])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

**Iterating**

In [ ]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [5]:
#Transpose
a2.shape

(3, 4)

In [13]:
a4=np.transpose(a2)
a4

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [10]:
a4.shape

(4, 3)

In [14]:
a4.T

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
#ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [19]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

**Stacking**

In [20]:
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)

In [21]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [24]:
#horizontal Stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [25]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

**Splitting**

In [26]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
#horizontal split
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [28]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [29]:
#vertical split
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]